name: build dev

on:
  push:
    branches:
      - dev
      - dev-*

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
         - version: '2.7.18'
           tags: 2
           suffix: msi
         - version: '3.10.3'
           tags: 3
           suffix: exe
        arch:
         - install_extra: wine64
           tag_suffix: "-${{ github.ref_name }}"
           suffix: amd64
         - tag_suffix: "-${{ github.ref_name }}-32"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Expand options
        run: ./expand.py "${{ matrix.python.tags }}" "${{ matrix.arch.tag_suffix }}" "${{ matrix.python.suffix }}" "${{ matrix.arch.suffix }}"
        id: expand-options
      - name: Show options
        run: |
          echo "Full tags ${{ steps.expand-options.outputs.full_tags }}"
          echo "Suffix ${{ steps.expand-options.outputs.python_suffix }}"

      - name: Login to GHCR
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: "${{ matrix.dockerfile.name }}"
          tags: "${{ steps.expand-options.outputs.full_tags }}"
          build-args: |
            PYTHON_VERSION=${{ matrix.python.version }}
            PYTHON_SUFFIX=${{ steps.expand-options.outputs.python_suffix }}
            INSTALL_EXTRA=${{ matrix.arch.install_extra }}
